/*Chạy code này để drop database
USE [master]
GO
ALTER DATABASE [EXAM_REGISTER] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
USE [master]
GO
DROP DATABASE [EXAM_REGISTER]
GO
*/
CREATE DATABASE EXAM_REGISTER
GO
USE EXAM_REGISTER
GO

/*-----------------PHẦN TẠO BẢNG VÀ KHÓA CHÍNH---------------------*/
-- CÁC CÔNG VIỆC CẦN LÀM:
-- + CHECK ERD VÀ KIỂU DỮ LIỆU CÁC THUỘC TÍNH
-- + THÊM RÀNG BUỘC CHO TỪNG THUỘC TÍNH (UNIQUE, NOT NULL, CHECK)
-- + XÁC ĐỊNH KHÓA NGOẠI VÀ THÊM RÀNG BUỘC KHÓA NGOẠI

-- 1
CREATE TABLE NHAN_VIEN (
    MA_NV CHAR(6), -- 
	HOTEN NVARCHAR(50),
    CCCD CHAR(12),
	SDT CHAR(10),
	EMAIL VARCHAR(50),
	LOAINV VARCHAR(30),
	CONSTRAINT PK_NHAN_VIEN PRIMARY KEY (MA_NV)
)
GO

-- 2
CREATE TABLE THI_SINH (
    MA_TS CHAR(6),
	SOBAODANH CHAR(6),
    HOTEN NVARCHAR(50),
	CCCD CHAR(12),
	NGAYSINH DATE,
	SDT CHAR(10),
	EMAIL VARCHAR(50),
	CONSTRAINT PK_THI_SINH PRIMARY KEY (MA_TS)
)
GO

-- 3
CREATE TABLE KHACH_HANG (
    MA_KH CHAR(6),
	SDT CHAR(10),
	EMAIL VARCHAR(50),
	LOAIKH NCHAR(7),
	CONSTRAINT PK_KHACH_HANG PRIMARY KEY (MA_KH)
)
GO

-- 4
CREATE TABLE KHACH_HANG_TUDO(
	MA_KHTD CHAR(6),
	HOTEN NVARCHAR(50),
	CONSTRAINT PK_KHACH_HANG_TUDO PRIMARY KEY (MA_KHTD)
)
GO

-- 5
CREATE TABLE KHACH_HANG_DONVI(
	MA_KHDV CHAR(6),
	DIACHI NVARCHAR(100),
	TENDONVI NVARCHAR(50),
	SOLUONGTHISINH INT, --??????????
	CONSTRAINT PK_KHACH_HANG_DONVI PRIMARY KEY (MA_KHDV)
)

-- 6
CREATE TABLE PHIEU_GIA_HAN (
    MA_PGH CHAR(6),
	NGAYLAP DATE,
    MON NVARCHAR(20),
	TRUONGHOP NVARCHAR(20),
	PHI INT,
	MA_NV CHAR(6),
	MA_TS CHAR (6),
	CONSTRAINT PK_PHIEU_GIA_HAN PRIMARY KEY (MA_PGH)
)
GO

-- 7
CREATE TABLE PHIEU_DANG_KY (
    MA_PDK CHAR(6),
	NGAYLAP DATE, -- NHỚ BỔ SUNG CÁI NÀY VÀO ERD
    NGAYDANGKY DATE,
	TINHTRANG NVARCHAR(20),
	MA_NV CHAR(6),
	CONSTRAINT PK_PHIEU_DANG_KY PRIMARY KEY (MA_PDK)
)
GO

-- 8
CREATE TABLE PHIEU_THANH_TOAN (
    MA_PTT CHAR(6),
	TINHTRANG VARCHAR(20), 
    NGAYLAP DATE,
	MA_NV CHAR(6),
	CONSTRAINT PK_PHIEU_THANH_TOAN PRIMARY KEY (MA_PTT)
)
GO

-- 9
CREATE TABLE CHUNG_CHI (
    MA_CC CHAR(6),
	NGAYCAP DATE, 
    KETQUA INT,
	TRANGTHAI NVARCHAR(20),
	CONSTRAINT PK_CHUNG_CHI PRIMARY KEY (MA_CC)
)
GO

-- 10
CREATE TABLE PHONG_THI (
    MA_PHONG CHAR(6),
	TENPHONG NVARCHAR(20),
	TRANGTHAI NVARCHAR(20),
	SOGHETOIDA INT,
	SOGHETRONG INT,
	CONSTRAINT PK_PHONG_THI PRIMARY KEY (MA_PHONG)
)
GO

-- 11
CREATE TABLE LICH_THI (
    MA_LICH CHAR(6),
	THOIGIAN TIME,
	CONSTRAINT PK_LICH_THI PRIMARY KEY (MA_LICH)
)
GO

-- 12
CREATE TABLE LOAI_DGNL (
    MA_LOAI CHAR(6),
	TENLOAI VARCHAR(20),
	GIATIEN INT,
	CONSTRAINT PK_LOAI_DGNL PRIMARY KEY (MA_LOAI)
)
GO

/*---------------PHẦN CÀI ĐẶT KHÓA NGOẠI-------------------------*/
-- TUI LÀM MẪU 1 CÁI CỦA PHIẾU GIA HẠN
ALTER TABLE PHIEU_GIA_HAN
ADD 
CONSTRAINT FK_PHIEUGIAHAN_NHANVIEN FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN(MA_NV),
CONSTRAINT FK_PHIEUGIAHAN_THISINH FOREIGN KEY (MA_TS) REFERENCES THI_SINH(MA_TS);
GO