
--Sp tìm kiếm ở trang của nhân viên kế toán - khách hàng tự do 
use EXAM_REGISTER
go 

-- Tìm danh sách thí sinh theo CCCD
GO
CREATE PROCEDURE SP_NVKT_TimKiemKHTD_Theo_CCCD
    @CCCD CHAR(12)
AS
BEGIN
    SELECT 
        TS.MA_TS,
        TS.HOTEN,
        TS.NGAYSINH,
        TS.CCCD,
        KH_TD.HOTEN AS NguoiDangKy,
        LD.GIATIEN AS SoTienCanTra,
        PTT.TINHTRANG AS TinhTrangThanhToan,
        PTT.MA_PTT  -- thêm MA_PTT
    FROM THI_SINH TS
    JOIN CHI_TIET_DANG_KY CTDK ON TS.MA_TS = CTDK.MA_TS
    JOIN PHIEU_DANG_KY PDK ON CTDK.MA_PDK = PDK.MA_PDK
    JOIN KHACH_HANG KH ON PDK.MA_KH = KH.MA_KH
    JOIN KHACH_HANG_TUDO KH_TD ON KH.MA_KH = KH_TD.MA_KHTD
    JOIN LICH_THI LT ON CTDK.MA_LICH = LT.MA_LICH
    JOIN LOAI_DGNL LD ON LT.MA_LOAI = LD.MA_LOAI
    LEFT JOIN PHIEU_THANH_TOAN PTT ON PDK.MA_PDK = PTT.MA_PDK
    WHERE TS.CCCD = @CCCD
    GROUP BY TS.MA_TS, TS.HOTEN, TS.NGAYSINH, TS.CCCD, KH_TD.HOTEN, LD.GIATIEN, PTT.TINHTRANG, PTT.MA_PTT
END

GO
-- Tìm danh sách thí sinh theo mã thí sinh
GO
CREATE PROCEDURE SP_NVKT_TimKiemKHTD_Theo_MA_TS
    @MA_TS CHAR(6)
AS
BEGIN
    SELECT 
        TS.MA_TS,
        TS.HOTEN,
        TS.NGAYSINH,
        TS.CCCD,
        KH_TD.HOTEN AS NguoiDangKy,
        LD.GIATIEN AS SoTienCanTra,
        PTT.TINHTRANG AS TinhTrangThanhToan,
        PTT.MA_PTT  -- thêm MA_PTT
    FROM THI_SINH TS
    JOIN CHI_TIET_DANG_KY CTDK ON TS.MA_TS = CTDK.MA_TS
    JOIN PHIEU_DANG_KY PDK ON CTDK.MA_PDK = PDK.MA_PDK
    JOIN KHACH_HANG KH ON PDK.MA_KH = KH.MA_KH
    JOIN KHACH_HANG_TUDO KH_TD ON KH.MA_KH = KH_TD.MA_KHTD
    JOIN LICH_THI LT ON CTDK.MA_LICH = LT.MA_LICH
    JOIN LOAI_DGNL LD ON LT.MA_LOAI = LD.MA_LOAI
    LEFT JOIN PHIEU_THANH_TOAN PTT ON PDK.MA_PDK = PTT.MA_PDK
    WHERE TS.MA_TS = @MA_TS
    GROUP BY TS.MA_TS, TS.HOTEN, TS.NGAYSINH, TS.CCCD, KH_TD.HOTEN, LD.GIATIEN, PTT.TINHTRANG, PTT.MA_PTT
END


GO
-- Tìm danh sách thí sinh theo tên
GO
CREATE PROCEDURE SP_NVKT_TimKiemKHTD_Theo_Ten_TS
    @HOTEN NVARCHAR(50)
AS
BEGIN
    SELECT 
        TS.MA_TS,
        TS.HOTEN,
        TS.NGAYSINH,
        TS.CCCD,
        KH_TD.HOTEN AS NguoiDangKy,
        LD.GIATIEN AS SoTienCanTra,
        PTT.TINHTRANG AS TinhTrangThanhToan,
        PTT.MA_PTT  -- thêm MA_PTT
    FROM THI_SINH TS
    JOIN CHI_TIET_DANG_KY CTDK ON TS.MA_TS = CTDK.MA_TS
    JOIN PHIEU_DANG_KY PDK ON CTDK.MA_PDK = PDK.MA_PDK
    JOIN KHACH_HANG KH ON PDK.MA_KH = KH.MA_KH
    JOIN KHACH_HANG_TUDO KH_TD ON KH.MA_KH = KH_TD.MA_KHTD
    JOIN LICH_THI LT ON CTDK.MA_LICH = LT.MA_LICH
    JOIN LOAI_DGNL LD ON LT.MA_LOAI = LD.MA_LOAI
    LEFT JOIN PHIEU_THANH_TOAN PTT ON PDK.MA_PDK = PTT.MA_PDK
    WHERE TS.HOTEN LIKE '%' + @HOTEN + '%'
    GROUP BY TS.MA_TS, TS.HOTEN, TS.NGAYSINH, TS.CCCD, KH_TD.HOTEN, LD.GIATIEN, PTT.TINHTRANG, PTT.MA_PTT
END


EXEC SP_NVKT_TimKiemKHTD_Theo_Ten_TS @HOTEN=N'Yến Đặng'
-- Tìm danh sách thí sinh theo mã thanh toán
GO
CREATE PROCEDURE SP_NVKT_TimKiemKHTD_Theo_MA_PTT
    @MA_PTT CHAR(6)
AS
BEGIN
    SELECT 
        TS.MA_TS,
        TS.HOTEN,
        TS.NGAYSINH,
        TS.CCCD,
        KH_TD.HOTEN AS NguoiDangKy,
        LD.GIATIEN AS SoTienCanTra,
        PTT.TINHTRANG AS TinhTrangThanhToan,
        PTT.MA_PTT  -- thêm MA_PTT
    FROM PHIEU_THANH_TOAN PTT
    JOIN PHIEU_DANG_KY PDK ON PTT.MA_PDK = PDK.MA_PDK
    JOIN CHI_TIET_DANG_KY CTDK ON CTDK.MA_PDK = PDK.MA_PDK
    JOIN THI_SINH TS ON TS.MA_TS = CTDK.MA_TS
    JOIN KHACH_HANG KH ON PDK.MA_KH = KH.MA_KH
    JOIN KHACH_HANG_TUDO KH_TD ON KH.MA_KH = KH_TD.MA_KHTD
    JOIN LICH_THI LT ON LT.MA_LICH = CTDK.MA_LICH
    JOIN LOAI_DGNL LD ON LD.MA_LOAI = LT.MA_LOAI
    WHERE PTT.MA_PTT = @MA_PTT
    GROUP BY TS.MA_TS, TS.HOTEN, TS.NGAYSINH, TS.CCCD, KH_TD.HOTEN, LD.GIATIEN, PTT.TINHTRANG, PTT.MA_PTT
END

EXEC SP_NVKT_TimKiemKHTD_Theo_MA_PTT @MA_PTT='TT0001'


-- Tìm danh sách chứng chỉ của khách hàng tự do theo CCCD
GO
CREATE PROCEDURE SP_NVKT_TimChungChiKHTD_Theo_CCCD
    @CCCD CHAR(12)
AS
BEGIN
    SELECT 
        CC.MONTHI AS TenChungChi,
        LD.GIATIEN
    FROM THI_SINH TS
    JOIN CHI_TIET_DANG_KY CTDK ON TS.MA_TS = CTDK.MA_TS
    JOIN LICH_THI LT ON CTDK.MA_LICH = LT.MA_LICH
    JOIN LOAI_DGNL LD ON LT.MA_LOAI = LD.MA_LOAI
    JOIN PHIEU_DANG_KY PDK ON CTDK.MA_PDK = PDK.MA_PDK
    JOIN KHACH_HANG KH ON PDK.MA_KH = KH.MA_KH
    JOIN KHACH_HANG_TUDO KHTD ON KH.MA_KH = KHTD.MA_KHTD
    JOIN CHUNG_CHI CC ON TS.MA_TS = CC.MA_TS 
    WHERE TS.CCCD = @CCCD
END

Exec SP_NVKT_TimChungChiKHTD_Theo_CCCD @CCCD='226997273935'

-- Tìm danh sách chứng chỉ của khách hàng tự do theo mã thí sinh
GO
CREATE PROCEDURE SP_NVKT_TimChungChiKHTD_Theo_Ma_TS
    @MA_TS CHAR(6)
AS
BEGIN
    SELECT 
        CC.MONTHI AS TenChungChi,
        LD.GIATIEN
    FROM THI_SINH TS
    JOIN CHI_TIET_DANG_KY CTDK ON TS.MA_TS = CTDK.MA_TS
    JOIN LICH_THI LT ON CTDK.MA_LICH = LT.MA_LICH
    JOIN LOAI_DGNL LD ON LT.MA_LOAI = LD.MA_LOAI
    JOIN PHIEU_DANG_KY PDK ON CTDK.MA_PDK = PDK.MA_PDK
    JOIN KHACH_HANG KH ON PDK.MA_KH = KH.MA_KH
    JOIN KHACH_HANG_TUDO KHTD ON KH.MA_KH = KHTD.MA_KHTD
    JOIN CHUNG_CHI CC ON TS.MA_TS = CC.MA_TS 
    WHERE TS.MA_TS = @MA_TS
END

EXEC SP_NVKT_TimChungChiKHTD_Theo_MA_TS @MA_TS='TS0001'

-- Tìm danh sách chứng chỉ của khách hàng tự do theo tên
GO
CREATE PROCEDURE SP_NVKT_TimChungChiKHTD_Theo_Ten
    @HOTEN NVARCHAR(50)
AS
BEGIN
    SELECT 
        CC.MONTHI AS TenChungChi,
        LD.GIATIEN
    FROM THI_SINH TS
    JOIN CHI_TIET_DANG_KY CTDK ON TS.MA_TS = CTDK.MA_TS
    JOIN LICH_THI LT ON CTDK.MA_LICH = LT.MA_LICH
    JOIN LOAI_DGNL LD ON LT.MA_LOAI = LD.MA_LOAI
    JOIN PHIEU_DANG_KY PDK ON CTDK.MA_PDK = PDK.MA_PDK
    JOIN KHACH_HANG KH ON PDK.MA_KH = KH.MA_KH
    JOIN KHACH_HANG_TUDO KHTD ON KH.MA_KH = KHTD.MA_KHTD
    JOIN CHUNG_CHI CC ON TS.MA_TS = CC.MA_TS 
    WHERE TS.HOTEN LIKE N'%' + @HOTEN + '%'
END

EXEC SP_NVKT_TimChungChiKHTD_Theo_Ten @HOTEN=N'Nguyễn Quang D'

-- Tìm danh sách chứng chỉ của khách hàng tự do theo phiếu thanh toán
GO
CREATE PROCEDURE SP_NVKT_TimChungChiKHTD_Theo_MA_PTT
    @MA_PTT CHAR(6)
AS
BEGIN
    SELECT 
        CC.MONTHI AS TenChungChi,
        LD.GIATIEN
    FROM THI_SINH TS
    JOIN CHI_TIET_DANG_KY CTDK ON TS.MA_TS = CTDK.MA_TS
    JOIN LICH_THI LT ON CTDK.MA_LICH = LT.MA_LICH
    JOIN LOAI_DGNL LD ON LT.MA_LOAI = LD.MA_LOAI
    JOIN PHIEU_DANG_KY PDK ON CTDK.MA_PDK = PDK.MA_PDK
    JOIN KHACH_HANG KH ON PDK.MA_KH = KH.MA_KH
    JOIN KHACH_HANG_TUDO KHTD ON KH.MA_KH = KHTD.MA_KHTD
    JOIN CHUNG_CHI CC ON TS.MA_TS = CC.MA_TS
    LEFT JOIN PHIEU_THANH_TOAN PTT ON PDK.MA_PDK = PTT.MA_PDK
    WHERE PTT.MA_PTT = @MA_PTT
    AND PTT.MA_PTT IS NOT NULL -- Chỉ trả về nếu có phiếu thanh toán
END
EXEC SP_NVKT_TimChungChiKHTD_Theo_MA_PTT @MA_PTT='TT0001'

--Tìm kiếm ở trang nhân viên kế toán - khách hàng đơn vị
-- Tìm kiếm khách hàng đơn vị theo tên
GO
CREATE PROCEDURE SP_NVKT_TimKiemKHDV_Theo_Ten
    @TENDONVI NVARCHAR(50)
AS
BEGIN
    SELECT 
        KHDV.TENDONVI,
        KH.EMAIL,
        PDK.MA_PDK,
        LD.GIATIEN AS TongTienCanTra,
        PTT.TINHTRANG AS TinhTrangThanhToan,
        PTT.MA_PTT -- thêm dòng này
    FROM KHACH_HANG_DONVI KHDV
    JOIN KHACH_HANG KH ON KHDV.MA_KHDV = KH.MA_KH
    JOIN PHIEU_DANG_KY PDK ON KH.MA_KH = PDK.MA_KH
    JOIN CHI_TIET_DANG_KY CTDK ON PDK.MA_PDK = CTDK.MA_PDK
    JOIN LICH_THI LT ON CTDK.MA_LICH = LT.MA_LICH
    JOIN LOAI_DGNL LD ON LT.MA_LOAI = LD.MA_LOAI
    LEFT JOIN PHIEU_THANH_TOAN PTT ON PDK.MA_PDK = PTT.MA_PDK
    WHERE KHDV.TENDONVI LIKE N'%' + @TENDONVI + '%'
    GROUP BY KHDV.TENDONVI, KH.EMAIL, PDK.MA_PDK, LD.GIATIEN, PTT.TINHTRANG, PTT.MA_PTT -- thêm PTT.MA_PTT vào GROUP BY
END

GO
EXEC SP_NVKT_TimKiemKHDV_Theo_Ten @TENDONVI=N'Công ty Bùi Tập Đoàn'

GO
ALTER PROCEDURE SP_NVKT_TimKiemKHDV_Theo_Ma_DV
    @MA_KH CHAR(6)
AS
BEGIN
    SELECT 
        KHDV.TENDONVI,
        KH.EMAIL,
        PDK.MA_PDK,
        LD.GIATIEN AS TongTienCanTra,
        PTT.TINHTRANG AS TinhTrangThanhToan,
        PTT.MA_PTT -- thêm dòng này
    FROM KHACH_HANG_DONVI KHDV
    JOIN KHACH_HANG KH ON KHDV.MA_KHDV = KH.MA_KH
    JOIN PHIEU_DANG_KY PDK ON KH.MA_KH = PDK.MA_KH
    JOIN CHI_TIET_DANG_KY CTDK ON PDK.MA_PDK = CTDK.MA_PDK
    JOIN LICH_THI LT ON CTDK.MA_LICH = LT.MA_LICH
    JOIN LOAI_DGNL LD ON LT.MA_LOAI = LD.MA_LOAI
    LEFT JOIN PHIEU_THANH_TOAN PTT ON PDK.MA_PDK = PTT.MA_PDK
    WHERE KH.MA_KH = @MA_KH
    GROUP BY KHDV.TENDONVI, KH.EMAIL, PDK.MA_PDK, LD.GIATIEN, PTT.TINHTRANG, PTT.MA_PTT -- thêm PTT.MA_PTT vào GROUP BY
END

GO
EXEC SP_NVKT_TimKiemKHDV_Theo_Ma_DV @MA_KH='KH0401'

-- Tìm kiếm khách hàng đơn vị theo mã phiếu thanh toán
GO
CREATE PROCEDURE SP_NVKT_TimKiemKHDV_Theo_MA_PTT
    @MA_PTT CHAR(6)
AS
BEGIN
    SELECT 
        KHDV.TENDONVI,
        KH.EMAIL,
        PDK.MA_PDK,
        LD.GIATIEN AS TongTienCanTra,
        PTT.TINHTRANG AS TinhTrangThanhToan,
        PTT.MA_PTT -- thêm dòng này
    FROM KHACH_HANG_DONVI KHDV
    JOIN KHACH_HANG KH ON KHDV.MA_KHDV = KH.MA_KH
    JOIN PHIEU_DANG_KY PDK ON KH.MA_KH = PDK.MA_KH
    JOIN CHI_TIET_DANG_KY CTDK ON PDK.MA_PDK = CTDK.MA_PDK
    JOIN LICH_THI LT ON CTDK.MA_LICH = LT.MA_LICH
    JOIN LOAI_DGNL LD ON LT.MA_LOAI = LD.MA_LOAI
    LEFT JOIN PHIEU_THANH_TOAN PTT ON PDK.MA_PDK = PTT.MA_PDK
    WHERE PTT.MA_PTT = @MA_PTT
    GROUP BY KHDV.TENDONVI, KH.EMAIL, PDK.MA_PDK, LD.GIATIEN, PTT.TINHTRANG, PTT.MA_PTT
END

GO

-- Tìm kiếm danh sách chứng chỉ của đơn vị theo mã đơn vị
ALTER PROCEDURE SP_NVKT_TimChungChiKHDV_Theo_Ma_DV
    @MA_KH CHAR(6)
AS
BEGIN
    SELECT 
        DISTINCT PDK.MA_PDK,
        LD.TENLOAI AS TenChungChi,
        PDK.SOLUONG,
        LT.NGAYTHI,
        LD.GIATIEN AS TongTienCanTra,
        PTT.TINHTRANG AS TinhTrangThanhToan,
        PTT.MA_PTT -- thêm dòng này
    FROM PHIEU_DANG_KY PDK
    JOIN KHACH_HANG KH ON KH.MA_KH = PDK.MA_KH
    JOIN KHACH_HANG_DONVI KHDV ON KHDV.MA_KHDV = KH.MA_KH
    JOIN CHI_TIET_DANG_KY CTDK ON CTDK.MA_PDK = PDK.MA_PDK
    JOIN LICH_THI LT ON LT.MA_LICH = CTDK.MA_LICH
    JOIN LOAI_DGNL LD ON LD.MA_LOAI = LT.MA_LOAI
    LEFT JOIN PHIEU_THANH_TOAN PTT ON PDK.MA_PDK = PTT.MA_PDK
    WHERE KH.LOAIKH = N'Đơn vị' 
      AND KH.MA_KH = @MA_KH
END


EXEC SP_NVKT_TimChungChiKHDV_Theo_Ma_DV @MA_KH='KH0401'

--Tìm kiếm danh sách chứng chỉ của đơn vị theo tên
GO
CREATE PROCEDURE SP_NVKT_TimChungChiKHDV_Theo_Ten
    @TENDONVI NVARCHAR(50)
AS
BEGIN
    SELECT 
        DISTINCT PDK.MA_PDK,
        LD.TENLOAI AS TenChungChi,
        PDK.SOLUONG,
        LT.NGAYTHI,
        LD.GIATIEN AS TongTienCanTra,
        PTT.TINHTRANG AS TinhTrangThanhToan,
        PTT.MA_PTT -- thêm dòng này
    FROM PHIEU_DANG_KY PDK
    JOIN KHACH_HANG KH ON KH.MA_KH = PDK.MA_KH
    JOIN KHACH_HANG_DONVI KHDV ON KHDV.MA_KHDV = KH.MA_KH
    JOIN CHI_TIET_DANG_KY CTDK ON CTDK.MA_PDK = PDK.MA_PDK
    JOIN LICH_THI LT ON LT.MA_LICH = CTDK.MA_LICH
    JOIN LOAI_DGNL LD ON LD.MA_LOAI = LT.MA_LOAI
    LEFT JOIN PHIEU_THANH_TOAN PTT ON PDK.MA_PDK = PTT.MA_PDK
    WHERE KHDV.TENDONVI LIKE N'%' + @TENDONVI + '%'
END

go
EXEC SP_NVKT_TimChungChiKHDV_Theo_Ten @TENDONVI=N'Công ty Bùi Tập Đoàn'

-- Tìm kiếm danh sách chứng chỉ của đơn vị theo mã phiếu thanh toán
GO
CREATE PROCEDURE SP_NVKT_TimChungChiKHDV_Theo_MA_PTT
    @MA_PTT CHAR(6)
AS
BEGIN
    SELECT 
        DISTINCT PDK.MA_PDK,
        LD.TENLOAI AS TenChungChi,
        PDK.SOLUONG,
        LT.NGAYTHI,
        LD.GIATIEN AS TongTienCanTra,
        PTT.TINHTRANG AS TinhTrangThanhToan,
        PTT.MA_PTT -- thêm dòng này
    FROM PHIEU_DANG_KY PDK
    JOIN KHACH_HANG KH ON KH.MA_KH = PDK.MA_KH
    JOIN KHACH_HANG_DONVI KHDV ON KHDV.MA_KHDV = KH.MA_KH
    JOIN CHI_TIET_DANG_KY CTDK ON CTDK.MA_PDK = PDK.MA_PDK
    JOIN LICH_THI LT ON LT.MA_LICH = CTDK.MA_LICH	
    JOIN LOAI_DGNL LD ON LD.MA_LOAI = LT.MA_LOAI
    LEFT JOIN PHIEU_THANH_TOAN PTT ON PDK.MA_PDK = PTT.MA_PDK
    WHERE PTT.MA_PTT = @MA_PTT
END

EXEC SP_NVKT_TimChungChiKHDV_Theo_MA_PTT @MA_PTT='TT0401'

-- Cập nhật tình trạng thanh toán
GO
CREATE PROCEDURE SP_NVKT_CapNhat_TinhTrangThanhToan
    @MA_PTT CHAR(6)
AS
BEGIN
    UPDATE PHIEU_THANH_TOAN
    SET TINHTRANG = N'Đã thanh toán'
    WHERE MA_PTT = @MA_PTT
END

--EXEC SP_NVKT_CapNhat_TinhTrangThanhToan @MA_PTT='TT0001', @TINHTRANG=N'Đã thanh toán'