USE EXAM_REGISTER
GO
--QUẢN LÝ NHÂN VIÊN
-- Thêm nhân viên
-- Xóa nhân viên

CREATE PROCEDURE SP_THEM_NHAN_VIEN
    @HOTEN NVARCHAR(50),
    @CCCD CHAR(12),
    @SDT CHAR(10),
    @EMAIL VARCHAR(50),
    @LOAINV NVARCHAR(30),
    @PASSWORD VARCHAR(50)  -- mật khẩu cho login
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @NewMaNV CHAR(6)

    -- Tạo mã NV tự động (VD: NV0001, NV0002, ...)
    SELECT @NewMaNV = 'NV' + RIGHT('0000' + CAST(ISNULL(MAX(CAST(SUBSTRING(MA_NV, 3, 4) AS INT)) + 1, 1) AS VARCHAR), 4)
    FROM NHAN_VIEN

    -- Thêm vào bảng nhân viên
    INSERT INTO NHAN_VIEN (MA_NV, HOTEN, CCCD, SDT, EMAIL, LOAINV)
    VALUES (@NewMaNV, @HOTEN, @CCCD, @SDT, @EMAIL, @LOAINV)

    -- Thêm tài khoản login tương ứng
    INSERT INTO USERS (MA_NV, EMAIL, PASSWORD)
    VALUES (@NewMaNV, @EMAIL, @PASSWORD)

    -- Trả về mã nhân viên vừa tạo
    SELECT @NewMaNV AS MaNhanVienMoi
END;
GO

--USERS
-- Đăng nhập
-- Quên mật khẩu
CREATE PROCEDURE SP_LOGIN
    @Email VARCHAR(50),
    @Password VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        U.MA_NV,
        NV.HOTEN,
        NV.LOAINV AS VaiTro
    FROM USERS U
    JOIN NHAN_VIEN NV ON U.MA_NV = NV.MA_NV
    WHERE U.EMAIL = @Email AND U.PASSWORD = @Password;
END;
GO

-- NHÂN VIÊN TIẾP NHẬN
-- HIỂN THỊ DANH SÁCH THÔNG TIN KHÁCH HÀNG
-- THÊM KHÁCH HÀNG

CREATE PROCEDURE sp_get_all_khach_hang
AS
BEGIN
    SET NOCOUNT ON;

    SELECT *
    FROM KHACH_HANG;
END;
GO

CREATE PROCEDURE sp_them_khach_hang
    @SDT CHAR(10),
    @EMAIL VARCHAR(50),
    @LOAIKH NCHAR(7),
    @HOTEN NVARCHAR(50) = NULL,
    @TENDONVI NVARCHAR(50) = NULL,
    @DIACHI NVARCHAR(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @MaKH CHAR(6);

    SELECT @MaKH = 'KH' + RIGHT('0000' + CAST(ISNULL(MAX(CAST(SUBSTRING(MA_KH, 3, 4) AS INT)) + 1, 1) AS VARCHAR), 4)
    FROM KHACH_HANG;

    INSERT INTO KHACH_HANG (MA_KH, SDT, EMAIL, LOAIKH)
    VALUES (@MaKH, @SDT, @EMAIL, @LOAIKH);

    IF @LOAIKH = N'Tự do'
        INSERT INTO KHACH_HANG_TUDO (MA_KHTD, HOTEN) VALUES (@MaKH, @HOTEN);
    ELSE IF @LOAIKH = N'Đơn vị'
        INSERT INTO KHACH_HANG_DONVI (MA_KHDV, TENDONVI, DIACHI) VALUES (@MaKH, @TENDONVI, @DIACHI);

    SELECT @MaKH AS MaKhachHangMoi;
END;
GO

---GIAHAN
---HIỂN THỊ THÔNG TIN THÍ SINH
CREATE PROC sp_get_thi_sinh_theo_cccd
	@cccd CHAR(12)
AS
BEGIN
	SELECT
		TS.MA_TS,
        HOTEN,
        CCCD,
        NGAYSINH,
        SDT,
        EMAIL,
        CT.SOBAODANH
	FROM THI_SINH TS
    JOIN CHI_TIET_DANG_KY CT ON TS.MA_TS = CT.MA_TS
    WHERE TS.CCCD = @cccd
END

GO

CREATE PROC sp_get_chung_chi_dang_ky
	@cccd CHAR(12)
AS
BEGIN
	SELECT
        L.TENLOAI,
        LT.NGAYTHI
    FROM THI_SINH TS
    JOIN CHI_TIET_DANG_KY CT ON TS.MA_TS = CT.MA_TS
    JOIN LICH_THI LT ON CT.MA_LICH = LT.MA_LICH
    JOIN LOAI_DGNL L ON LT.MA_LOAI = L.MA_LOAI
    WHERE TS.CCCD = @cccd
END

GO

CREATE PROCEDURE sp_get_ngay_thi_con_ghe_trong
    @MON_THI NVARCHAR(50)
AS
BEGIN
    SELECT DISTINCT
        LT.NGAYTHI,
        LT.MA_LICH,
        CT.MA_PHONG
    FROM LICH_THI LT
    JOIN LOAI_DGNL LD ON LT.MA_LOAI = LD.MA_LOAI
    JOIN CHI_TIET_LICH_THI CT ON CT.MA_LICH = LT.MA_LICH
    WHERE LD.TENLOAI = @MON_THI AND CT.SOGHETRONG > 0
END

GO

CREATE PROCEDURE sp_update_lich_thi_gia_han
    @CCCD CHAR(12),
    @MON_THI VARCHAR(20),
    @MA_LICH_MOI CHAR(6),
    @MA_PHONG_MOI CHAR(6)
AS
BEGIN
    DECLARE @MA_LICH_CU CHAR(6), @MA_PHONG_CU CHAR(6);

    -- Lấy mã lịch và mã phòng cũ
    SELECT TOP 1
        @MA_LICH_CU = CT.MA_LICH,
        @MA_PHONG_CU = CT.MA_PHONG
    FROM CHI_TIET_DANG_KY CT
    JOIN THI_SINH TS ON TS.MA_TS = CT.MA_TS
    JOIN CHI_TIET_LICH_THI CTLT ON CT.MA_LICH = CTLT.MA_LICH AND CT.MA_PHONG = CTLT.MA_PHONG
	JOIN LICH_THI LT ON LT.MA_LICH = CTLT.MA_LICH
	JOIN LOAI_DGNL L ON L.MA_LOAI = LT.MA_LOAI
    WHERE TS.CCCD = @CCCD AND L.TENLOAI = @MON_THI;

    -- Cập nhật lịch thi mới và phòng thi mới vào bảng CHI_TIET_DANG_KY
    UPDATE CT
    SET CT.MA_LICH = @MA_LICH_MOI,
        CT.MA_PHONG = @MA_PHONG_MOI
    FROM CHI_TIET_DANG_KY CT
    JOIN THI_SINH TS ON TS.MA_TS = CT.MA_TS
    JOIN CHI_TIET_LICH_THI CTLT ON CT.MA_LICH = CTLT.MA_LICH AND CT.MA_PHONG = CTLT.MA_PHONG
    JOIN LICH_THI LT ON LT.MA_LICH = CTLT.MA_LICH
    JOIN LOAI_DGNL L ON L.MA_LOAI = LT.MA_LOAI
    WHERE TS.CCCD = @CCCD AND L.TENLOAI = @MON_THI;

    -- Tăng ghế trống cho lịch/phòng cũ
    UPDATE CHI_TIET_LICH_THI
    SET SOGHETRONG = SOGHETRONG + 1
    WHERE MA_LICH = @MA_LICH_CU AND MA_PHONG = @MA_PHONG_CU;

    -- Giảm ghế trống cho lịch/phòng mới
    UPDATE CHI_TIET_LICH_THI
    SET SOGHETRONG = SOGHETRONG - 1
    WHERE MA_LICH = @MA_LICH_MOI AND MA_PHONG = @MA_PHONG_MOI;
END
